const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94784604369"
const SESSION_ID = "PRABATH-MD~onkE0LJb#IwOF5HMGqZAOHrXff3A_mXd_rioGVFKjz9Izj6r0-zg"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
